###

GET http://localhost:8080/direccion/2


###

GET http://localhost:8080/direccion


###


POST http://localhost:8080/direccion
Content-Type: application/json
Accept: application/json

{
     "IdDepartamento": 13,
     "Departamento": "Litoral"
}


###



DELETE http://localhost:8080/departamento/1