###

GET http://localhost:8080/departamento/3


###

GET http://localhost:8080/departamento


###


POST http://localhost:8080/departamento
Content-Type: application/json
Accept: application/json

{
     "IdDepartamento": 13,
     "Departamento": "Litoral"
}


###



DELETE http://localhost:8080/departamento/1