###

GET http://localhost:8888/direccion/3


###

GET http://localhost:8888/direccion


###


POST http://localhost:8888/direccion
Content-Type: application/json
Accept: application/json

{
     "zona": "zona - 14",
     "calle": "calle - 14",
     "ciudad": "ciudad - 14",
     "departamento": "departamento - 14"
}


###

DELETE http://localhost:8080/departamento/1