###

GET http://localhost:8888/direccion/89


###

GET http://localhost:8888/direccion


###


POST http://localhost:8888/direccion
Content-Type: application/json
Accept: application/json

{
     "zona": "olvidos",
     "calle": "el olvido",
     "ciudad": "Oruro",
     "departamento": "Oruro"
}


###

DELETE http://localhost:8080/departamento/1