####

GET http://localhost:8888/recompensa


###

GET http://localhost:8888/recompensa/57

###

POST http://localhost:8888/recompensa
Content-Type: application/json
Accept: application/json

{
  "rangoInicial": "100",
  "rangoFinal": 200,
  "recompensa": "Oruroasdasdasd",
  "idProyecto": 3
}