####

GET http://localhost:8888/recompensa


###

GET http://localhost:8888/recompensa/2

###

POST http://localhost:8888/recompensa
Content-Type: application/json
Accept: application/json

{
  "rangoInicial": 250,
  "rangoFinal": 300,
  "recompensa": "Recompensa - 3",
  "idProyecto": 2
}