###

GET http://localhost:8080/direccionDTO/2



###

POST http://localhost:8080/user
Content-Type: application/json
Accept: application/json

{
  "idUsuario": "90",
  "username": "Ivan",
  "contrasenia": "1234124",
  "correoElectronico": "tipo@gmail.com",
  "telefono": "98465621",
  "tipoUsuario": "2"
}